from _typeshed import Incomplete

__all__ = ['csin', 'ccos', 'ctan', 'infinity']

infinity: Incomplete

def csin(z: complex, /, n: int = ...) -> complex: ...
def ccos(z: complex, /, n: int = ...) -> complex: ...
def ctan(z: complex, /, n: int = ...) -> complex: ...
