__all__ = ['csin0', 'ccos0', 'ctan0']

def csin0(z: complex, /, n: int = ...) -> complex: ...
def ccos0(z: complex, /, n: int = ...) -> complex: ...
def ctan0(z: complex, /, n: int = ...) -> complex: ...
