__all__ = ['exp0', 'exp', 'cexp0', 'cexp']

def exp0(x: float, /, n: int = 22) -> float: ...
def exp(x: float, /, n: int = 22) -> float: ...
def cexp0(z: complex, /, n: int = 22) -> complex: ...
def cexp(z: complex, /, n: int = 22) -> complex: ...
