__all__ = ['exp0', 'exp', 'cexp0', 'cexp']

def exp0(x: float, /, n: int = ...) -> float: ...
def exp(x: float, /, n: int = ...) -> float: ...
def cexp0(z: complex, /, n: int = ...) -> complex: ...
def cexp(z: complex, /, n: int = ...) -> complex: ...
