__all__ = ['sin0', 'cos0', 'tan0', 'maxdepth', 'mindepth']

maxdepth: int
mindepth: int

def sin0(θ: float, /, n: int = ...) -> float: ...
def cos0(θ: float, /, n: int = ...) -> float: ...
def tan0(θ: float, /, n: int = ...) -> float: ...
